version: '3'
services:
  backend: 
    build: .
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001
    environment:
      MYSQL_HOSTNAME: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE_NAME: TrybeWalletDB
      MYSQL_PORT: 3306
    env_file:
      - .env
    depends_on:
      - db

  db: 
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TrybeWalletDB
    volumes:
      - ./src/db/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
    